### PR TITLE
Update file fields

### PR DESCRIPTION
**Pull request by jbickar**
See BASIC-872

### CODE REVIEW

**Comment by sherakama** [comment]
Looks great. 
Silly thing has checkbox for display set to checked by default while the feature has display_default = 0. I tried several combinations of the display display_default and field_display but none seem to take. 

Looking at the field definition code it looks like it should work but it doesn't.

'#value' => isset($item['display']) ? $item['display'] : $field['settings']['display_default'],

**Comment by jbickar** [comment]
Hrmph, yeah, that's weird, I'm seeing the same thing. "Display" checkbox is getting checked by default when creating a stanford_page node.

Lemme see if it's something in the insert settings?

**Comment by sherakama** [comment]
I tried to get it to set the checkbox to unchecked by default but I cannot. Not spending any more time on this for now. Im going to merge and we can fix it later

**Comment by jbickar** [comment]
Good by me. We were kind of waffling on it anyhow.

**Pull request merged**
